[package]
name = "qrcode"
description = "QR code encoder in Rust"
license = "MIT / Apache-2.0"
version = "0.3.0"
authors = ["kennytm <kennytm@gmail.com>"]
keywords = ["qrcode"]
repository = "https://github.com/kennytm/qrcode-rust"
readme = "README.md"
documentation = "http://docs.rs/qrcode"
exclude = [
    ".travis.yml", ".gitignore", "test-data/**"
]

[badges]
travis-ci = { repository = "kennytm/qrcode-rust" }

[dependencies]
image = { version = "0.13", optional = true }

[features]
default = ["image"]
bench = []

[[bin]]
name = "qrencode"
